name: Test Automation Workflow

on:
  schedule:
    - cron: '30 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
           
      - name: Running Test Automation Framework with Maven
        run: mvn clean test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
        env:
          THIS_IS_A_VARIABLE_USERNAME: ${{secrets.username}}

      - name: Upload Test logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: TestLogs
          path: logs/
        
      - name: Upload Test reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: extent-reports
          path: reports/

      - name: Test Execution Status
        run: echo "Test Exeution Completed"
 
