name: Test Automation Workflow

on:
  schedule:
    - cron: '30 3 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: TestLogs
        path: logs/
        
    - name: Upload Test reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: TestReport
        path: report.html

    - name: Test Execution Status
      run: echo "Test Exeution Completed"
 
